### PR TITLE
Select the correct file if we have installed the Rainlab translate plugi...

### PR DESCRIPTION
**Pull request by CGGStudio**
When we have several files in different languages do not always choose the right and the principal is selected. With this arrangement solves the problem.

### CODE REVIEW

**Comment by daftspunk** [comment]
Compare with #13 and determine which is better

**Comment by CGGStudio** [comment]
It seems perfect.
A greeting.
Carlos

**Comment by daftspunk** [comment]
I actually think this one is better, it is based on [existing works](https://github.com/rainlab/translate-plugin/blob/master/Plugin.php#L91-L94).

**Comment by daftspunk** [comment]
Thanks!

**Pull request merged**
