### PR TITLE
Added composer.json

### PR DESCRIPTION
**Pull request by acasar**
Refs: https://github.com/rainlab/translate-plugin/issues/146

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
How about include composer/installers package? See last comment here: https://github.com/rainlab/googleanalytics-plugin/pull/24#issuecomment-163397261

**Comment by acasar** [comment]
In my tests this was enough:

```
"type": "october-plugin"
```

Since the base october installation already requires composer/installers.

**Comment by vojtasvoboda** [comment]
I don't know man, I think good idea is include `composer/installers` each time you are using `type` in composer file.

For example both https://github.com/octoberrain/cms/blob/master/composer.json and https://github.com/octoberrain/backend/blob/master/composer.json are requiring  `composer/installer`. And it is also "redundancy" as you say.

**Comment by acasar** [comment]
If we're adding the ``require`` block then we should probably handle plugin dependencies as well... I guess I'll handle this then.

**Comment by vojtasvoboda** [comment]
I am not sure, so I placed question here https://github.com/rainlab/translate-plugin/issues/146

**Pull request merged**
